version: '2'
services:
  api:
    container_name: doubtfire-api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/doubtfire-api
      - /doubtfire-api/.bundle
      - /doubtfire-api/tmp
 
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://itig:d872$$dh@db:5432/doubtfire_dev'
      RAILS_ENV: 'development'

  db:
    container_name: doubtfire-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: d872$$dh
      POSTGRES_USER: itig

  