development: &development
  secret_key_base:   <%= ENV['DF_SECRET_KEY_BASE']   || SecureRandom.base64 %>
  secret_key_attr:   <%= ENV['DF_SECRET_KEY_ATTR']   || SecureRandom.base64 %>
  secret_key_devise: <%= ENV['DF_SECRET_KEY_DEVISE'] || SecureRandom.base64 %>
  secret_key_aaf:    <%= ENV['DF_SECRET_KEY_AAF']    || 'secretsecret12345' %>
test:
  # <<: *development
replica:
  # <<: *development
production:
  secret_key_base:   <%= ENV['DF_SECRET_KEY_BASE']   %>
  secret_key_attr:   <%= ENV['DF_SECRET_KEY_ATTR']   %>
  secret_key_devise: <%= ENV['DF_SECRET_KEY_DEVISE'] %>
  secret_key_aaf:    <%= ENV['DF_SECRET_KEY_AAF']    %>
